### ISSUE TITLE
programming the board

### ISSUE THREAD

**Issue by bulnv** [SvenHaedrich/m122_keyboard#2]
Hello Sven! I was trying to reach out to you in deskthority forum. Here is my question:

I recently found your 122 key ibm restoration project and really excited about it. I'm an doing right now the same. I have a board without controller and I'd wanted to reuse your PCB design. I am mostly software guy, and only one thing is confusing me it's a initial firmware with some jtag. Is it kinda must and there no other way ways like usb? If so, can you please point me the correct one flashing device? Thanks!

**Comment by SvenHaedrich** [comment]
Obviously, GitHub has a better connection to me than deskthority.net. 

I never bothered to find out how to flash the nRF without a SWD programmer at hand. As far as I recall there is no hardcoded bootloader included in the nRF. So, you have two options:

(1) If you want to replicate my hardware: I still have some PCBs left. I can flash a bootloader and a keyboard driver onto the  board before I send it out to you. Once you have a bootloader installed you can flash the keyboard driver via drag´n´drop to the controller.
(2) If you want to modify the layout: you can swap the TAG connect (actually the connector would be more expensive than a programmer) to something more common and use a variety of programmers to flash the board (see e.g. https://github.com/kholia/xvc-pico/ )

**Comment by bulnv** [comment]
Hello! Thanks for response. Having PCB from you would be the best option I could imagine, especially preflashed. My email is nvbulashev@gmail.com.

**Comment by SvenHaedrich** [comment]
You have mail.

**Comment by GrimbleFitz** [comment]
Hey Sven! I also noticed your post on Deskthority and would be very appreciative if you still had some PCBs left. I've got a couple of m122's without controllers that I've been hoping to engineer some sort of battery+wireless ZMK solution for. My email is kile@fitz.farm, if you don't mind me chiming in like this.

**Comment by SvenHaedrich** [comment]
Issues solved.
